
stages:
  - lint
  - test
  - docker

sudo: true
language: python

install:
  - pip install -U setuptools pip
  - pip install tox
  - sudo apt-get install graphviz
script:
  - tox
after_success:
  - source .tox/${TOXENV}/bin/activate && pip install codecov && codecov

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning

jobs:
  # mask to select which jobs are allowed to fail
  allow_failures:
    - python: nightly
    - stage: docker
  include:
    - stage: lint
      python: 3.6
      env: TOXENV=bandit
    - python: 3.6
      env: TOXENV=format
    - python: 3.6
      env: TOXENV=lint
      script:
        - bash -c 'shopt -s globstar nullglob; shellcheck **/*.sh'
        - tox
    - python: 3.6
      env: TOXENV=docs

    - stage: test
      python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial      # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required    # required for Python 3.7 (travis-ci/travis-ci#9069)
    - python: nightly
      env: TOXENV=py38
      dist: xenial      # required for Python 3.8 (travis-ci/travis-ci#9069)
      sudo: required    # required for Python 3.8 (travis-ci/travis-ci#9069)

    - stage: docker
      script: docker build .
