sudo: false
language: python
install:
  - pip install -U setuptools pip
  - pip install tox
script:
  - tox
after_success:
  - source .tox/${TOXENV}/bin/activate && pip install codecov && codecov

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOXENV=lint
    - TOXENV=docs
    - TOXENV=py27
    - TOXENV=el7
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
