sudo: true
language: python
install:
  - pip install -U setuptools pip
  - pip install tox
  - sudo apt-get install graphviz
script:
  - tox
after_success:
  - source .tox/${TOXENV}/bin/activate && pip install codecov && codecov

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOXENV=lint
    - TOXENV=py27
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial      # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required    # required for Python 3.7 (travis-ci/travis-ci#9069)
    - python: nightly
      env: TOXENV=py38
      dist: xenial      # required for Python 3.8 (travis-ci/travis-ci#9069)
      sudo: required    # required for Python 3.8 (travis-ci/travis-ci#9069)
    - python: 3.6
      env: TOXENV=docs
  allow_failures:
    - python: nightly
