language: python
os: linux
dist: trusty

stages:
  - lint
  - test
  - docker

install:
  # Graphiviz is used to generate database schema, see tox.ini
  - sudo apt-get -y install graphviz tox
script:
  - tox
after_success:
  - source .tox/${TOXENV}/bin/activate && pip install codecov && codecov

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning

jobs:
  # mask to select which jobs are allowed to fail
  allow_failures:
    - python: nightly
    - stage: docker
  include:
    - stage: lint
      python: 3.6
      env: TOXENV=bandit
    - python: 3.6
      env: TOXENV=format
    - python: 3.6
      env: TOXENV=lint
      script:
        - bash -c 'shopt -s globstar nullglob; shellcheck **/*.sh'
        - tox
    - python: 3.6
      env: TOXENV=docs

    - stage: test
      python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: nightly
      env: TOXENV=py39

    - stage: docker
      script:
        - docker build . -t anitya
        - docker run -d anitya
        - docker ps -a
